Implement UI and Logic
emmyobonyo/Awesome-Books pull request #3
Opened 2021-07-05 20:06 UTC by emmyobonyo

- Created Medium Level Wire UI for the App.
- Implemented logic to allow a user to Add a Book.
- Implemented Logic to allow a user Remove  a Book.

2021-07-05 20:19 UTC, mricanho requested changes
Hi @emmyobonyo @yahyaelganyni1, 

You did a great job with this app, the linters are up and running and you did good commit messages🔥🔥 

There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

![almost there](https://user-images.githubusercontent.com/60631456/124515163-5aa3ee80-dda4-11eb-8cad-8082e431bec1.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-05 20:19 UTC, mricanho commented on index.js
> +    bookList.removeChild(li);
- [ ] [OPTIONAL] Break this function, remember that a function must do one thing and one thing only.

2021-07-05 20:19 UTC, mricanho commented on index.js
> +
- [ ] Add a function to use Local Storage, data must be preserved in the browser's memory by using Local Storage, [check this link](https://github.com/microverseinc/curriculum-html-css/blob/main/local_storage.md)

2021-07-06 07:58 UTC, bellom approved these changes
Hi Team 👏  

**Great work making all the necessary corrections from the previous review.**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-06 07:58 UTC, bellom commented on README.md
>  👤 **Author2**
# [Optional]
Heads-Up: Instead of `Author2`, It would be nice to put the name of the Author right?
Kindly do this before merging 👍

2021-07-06 09:38 UTC, merged